import Foundation

extension CampaignLibrary {
    static func buildChapter6() -> CampaignChapter {
        let stage61 = targetStage(chapter: 6, index: 1, title: "制限デッキ基礎", summary: "障害物のある盤面で、軽めのデッキだけで目的地へ寄せます。", goalCount: 10, deckPreset: .standardLight, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 355, unlockRequirement: .chapterTotalStars(chapter: 5, minimum: 12), impassableTilePoints: [GridPoint(x: 1, y: 1), GridPoint(x: 3, y: 3)])
        let stage62 = targetStage(chapter: 6, index: 2, title: "王将と桂馬", summary: "限られた移動種で、障害物を避ける道筋を作ります。", goalCount: 11, deckPreset: .kingAndKnightBasic, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 28), scoreTarget: 380, unlockRequirement: .stageClear(stage61.id), impassableTilePoints: [GridPoint(x: 2, y: 1), GridPoint(x: 2, y: 3)])
        let stage63 = targetStage(chapter: 6, index: 3, title: "縦横制限", summary: "縦横選択に寄せたデッキで、軸を合わせて目的地を取ります。", goalCount: 11, deckPreset: .kingAndKnightWithOrthogonalChoices, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 375, unlockRequirement: .stageClear(stage62.id), impassableTilePoints: [GridPoint(x: 1, y: 2), GridPoint(x: 3, y: 2)])
        let stage64 = targetStage(chapter: 6, index: 4, title: "斜め制限", summary: "斜め選択で抜け道を作り、詰まりそうな盤面を崩します。", goalCount: 12, deckPreset: .kingAndKnightWithDiagonalChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 30), scoreTarget: 405, unlockRequirement: .stageClear(stage63.id), impassableTilePoints: [GridPoint(x: 0, y: 2), GridPoint(x: 2, y: 2), GridPoint(x: 4, y: 2)])
        let stage65 = targetStage(chapter: 6, index: 5, title: "跳躍制限", summary: "桂馬選択を軸に、障害物越しの目的地へ近づきます。", goalCount: 12, deckPreset: .kingAndKnightWithKnightChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 400, unlockRequirement: .stageClear(stage64.id), impassableTilePoints: [GridPoint(x: 1, y: 1), GridPoint(x: 2, y: 2), GridPoint(x: 3, y: 3)])
        let stage66 = targetStage(chapter: 6, index: 6, title: "長距離制御", summary: "連続移動カードで進みすぎないよう、目的地手前の位置を選びます。", goalCount: 13, deckPreset: .directionalRayFocus, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 31), scoreTarget: 425, unlockRequirement: .stageClear(stage65.id), impassableTilePoints: [GridPoint(x: 1, y: 3), GridPoint(x: 3, y: 1)])
        let stage67 = targetStage(chapter: 6, index: 7, title: "制限総合", summary: "障害物とデッキ制限を読み、必要な時だけフォーカスを使います。", goalCount: 13, deckPreset: .standardWithAllChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 2), scoreTarget: 420, unlockRequirement: .stageClear(stage66.id), impassableTilePoints: [GridPoint(x: 0, y: 1), GridPoint(x: 2, y: 2), GridPoint(x: 4, y: 3)])
        let stage68 = targetStage(chapter: 6, index: 8, title: "制限試験", summary: "限られた通路とカードを使い、目的地を安定して集めます。", goalCount: 14, deckPreset: .standardWithAllChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMostAndWithinMoves(maxFocusCount: 3, maxMoves: 33), scoreTarget: 450, unlockRequirement: .stageClear(stage67.id), impassableTilePoints: [GridPoint(x: 1, y: 1), GridPoint(x: 1, y: 3), GridPoint(x: 3, y: 1), GridPoint(x: 3, y: 3)])

        return CampaignChapter(id: 6, title: "制限と迂回", summary: "障害物とデッキ制限を組み合わせる章。", stages: [stage61, stage62, stage63, stage64, stage65, stage66, stage67, stage68])
    }
}
