import Foundation

extension CampaignLibrary {
    static func buildChapter8() -> CampaignChapter {
        let cornerTargets = [MoveCard.fixedWarp: [GridPoint(x: 0, y: 0), GridPoint(x: 4, y: 0), GridPoint(x: 4, y: 4), GridPoint(x: 0, y: 4)]]
        let edgeTargets = [MoveCard.fixedWarp: [GridPoint(x: 0, y: 2), GridPoint(x: 2, y: 0), GridPoint(x: 4, y: 2), GridPoint(x: 2, y: 4)]]
        let crossWarp = ["cross": [GridPoint(x: 0, y: 4), GridPoint(x: 4, y: 0)]]
        let ringWarp = ["ring": [GridPoint(x: 0, y: 0), GridPoint(x: 4, y: 0), GridPoint(x: 4, y: 4), GridPoint(x: 0, y: 4)]]

        let stage81 = targetStage(chapter: 8, index: 1, title: "固定ワープ基礎", summary: "固定ワープカードで遠い表示目的地へ一気に近づきます。", goalCount: 10, deckPreset: .fixedWarpSpecialized, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 350, unlockRequirement: .stageClear(CampaignStageID(chapter: 7, index: 8)), fixedWarpCardTargets: cornerTargets)
        let stage82 = targetStage(chapter: 8, index: 2, title: "辺への転移", summary: "辺の固定ワープ先を使い、目的地への入口を選びます。", goalCount: 11, deckPreset: .fixedWarpSpecialized, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 27), scoreTarget: 375, unlockRequirement: .stageClear(stage81.id), fixedWarpCardTargets: edgeTargets)
        let stage83 = targetStage(chapter: 8, index: 3, title: "全域ワープ", summary: "全域ワープで遠距離目的地を狙い、着地点から微調整します。", goalCount: 11, deckPreset: .superWarpHighFrequency, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 370, unlockRequirement: .stageClear(stage82.id))
        let stage84 = targetStage(chapter: 8, index: 4, title: "ワープ併用", summary: "ワープカードと通常カードを組み合わせ、近距離と遠距離を切り替えます。", goalCount: 12, deckPreset: .standardWithWarpCards, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 30), scoreTarget: 405, unlockRequirement: .stageClear(stage83.id), warpTilePairs: crossWarp)
        let stage85 = targetStage(chapter: 8, index: 5, title: "障害物転移", summary: "障害物を越えるために、固定ワープと全域ワープを使い分けます。", goalCount: 12, deckPreset: .standardWithWarpCards, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 2), scoreTarget: 400, unlockRequirement: .stageClear(stage84.id), impassableTilePoints: [GridPoint(x: 2, y: 2)], fixedWarpCardTargets: cornerTargets)
        let stage86 = targetStage(chapter: 8, index: 6, title: "特殊マス混成", summary: "ワープと手札補助の特殊マスを両方使い、目的地への距離を縮めます。", goalCount: 13, deckPreset: .targetLabAllIn, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 32), scoreTarget: 430, unlockRequirement: .stageClear(stage85.id), tileEffectOverrides: [GridPoint(x: 1, y: 3): .nextRefresh, GridPoint(x: 3, y: 1): .freeFocus, GridPoint(x: 2, y: 2): .targetSwap], warpTilePairs: crossWarp, fixedWarpCardTargets: edgeTargets)
        let stage87 = targetStage(chapter: 8, index: 7, title: "空間支配", summary: "遠距離移動、ワープ、加速を使い、フォーカスの回数を抑えます。", goalCount: 13, deckPreset: .standardWithWarpCards, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 2), scoreTarget: 425, unlockRequirement: .stageClear(stage86.id), impassableTilePoints: [GridPoint(x: 1, y: 1), GridPoint(x: 3, y: 3)], tileEffectOverrides: [GridPoint(x: 2, y: 1): .boost, GridPoint(x: 2, y: 3): .slow], warpTilePairs: ringWarp, fixedWarpCardTargets: cornerTargets)
        let stage88 = targetStage(chapter: 8, index: 8, title: "目的地制最終試験", summary: "表示中の目的地、フォーカス、障害物、特殊マス、ワープを総動員して取り切る最終試験です。", goalCount: 14, deckPreset: .targetLabAllIn, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMostAndWithinMoves(maxFocusCount: 3, maxMoves: 34), scoreTarget: 455, unlockRequirement: .stageClear(stage87.id), impassableTilePoints: [GridPoint(x: 0, y: 0), GridPoint(x: 2, y: 2), GridPoint(x: 4, y: 4)], tileEffectOverrides: [GridPoint(x: 0, y: 2): .nextRefresh, GridPoint(x: 2, y: 0): .preserveCard, GridPoint(x: 4, y: 2): .draft, GridPoint(x: 2, y: 4): .overload, GridPoint(x: 1, y: 3): .targetSwap], warpTilePairs: crossWarp, fixedWarpCardTargets: edgeTargets)

        return CampaignChapter(id: 8, title: "空間支配", summary: "ワープカードと特殊マスを組み合わせ、全要素で目的地を取り切る章。", stages: [stage81, stage82, stage83, stage84, stage85, stage86, stage87, stage88])
    }
}
