import Foundation

extension CampaignLibrary {
    static func buildChapter5() -> CampaignChapter {
        let stage51 = targetStage(chapter: 5, index: 1, title: "障害物基礎", summary: "障害物を避けながら、表示中の目的地へ回り込む基本を学びます。", goalCount: 10, deckPreset: .standardWithAllChoices, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 350, unlockRequirement: .stageClear(CampaignStageID(chapter: 4, index: 8)), impassableTilePoints: [GridPoint(x: 1, y: 1), GridPoint(x: 3, y: 3)])
        let stage52 = targetStage(chapter: 5, index: 2, title: "中央回避", summary: "中央を避け、左右どちらから目的地へ寄せるか選びます。", goalCount: 10, deckPreset: .standardWithAllChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 24), scoreTarget: 350, unlockRequirement: .stageClear(stage51.id), impassableTilePoints: [GridPoint(x: 2, y: 2)])
        let stage53 = targetStage(chapter: 5, index: 3, title: "開門の一手", summary: "開門マスで障害物を消し、次の目的地へ通る道を作ります。", goalCount: 11, deckPreset: .standardWithAllChoices, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 375, unlockRequirement: .stageClear(stage52.id), impassableTilePoints: [GridPoint(x: 3, y: 2)], tileEffectOverrides: [GridPoint(x: 0, y: 2): .openGate(target: GridPoint(x: 3, y: 2))])
        let stage54 = targetStage(chapter: 5, index: 4, title: "細道と開門", summary: "細い通路と開門を読み、表示目的地への入口を増やします。", goalCount: 11, deckPreset: .standardWithOrthogonalChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 26), scoreTarget: 375, unlockRequirement: .stageClear(stage53.id), impassableTilePoints: [GridPoint(x: 1, y: 2), GridPoint(x: 2, y: 2), GridPoint(x: 3, y: 2)], tileEffectOverrides: [GridPoint(x: 2, y: 0): .openGate(target: GridPoint(x: 2, y: 2))])
        let stage55 = targetStage(chapter: 5, index: 5, title: "斜め迂回", summary: "斜め選択カードで障害物の横を抜け、目的地へ近づきます。", goalCount: 12, deckPreset: .standardWithDiagonalChoices, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 400, unlockRequirement: .stageClear(stage54.id), impassableTilePoints: [GridPoint(x: 1, y: 1), GridPoint(x: 3, y: 3), GridPoint(x: 2, y: 4)])
        let stage56 = targetStage(chapter: 5, index: 6, title: "跳躍迂回", summary: "桂馬選択で障害物の影響を越え、遠い目的地へ寄せます。", goalCount: 12, deckPreset: .standardWithKnightChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 28), scoreTarget: 395, unlockRequirement: .stageClear(stage55.id), impassableTilePoints: [GridPoint(x: 1, y: 3), GridPoint(x: 2, y: 2), GridPoint(x: 3, y: 1)])
        let stage57 = targetStage(chapter: 5, index: 7, title: "開門総合", summary: "複数の障害物と開門を読み、近い目的地から安全に集めます。", goalCount: 12, deckPreset: .targetLabAllIn, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 2), scoreTarget: 390, unlockRequirement: .stageClear(stage56.id), impassableTilePoints: [GridPoint(x: 0, y: 2), GridPoint(x: 2, y: 0), GridPoint(x: 4, y: 2)], tileEffectOverrides: [GridPoint(x: 2, y: 4): .openGate(target: GridPoint(x: 2, y: 0))])
        let stage58 = targetStage(chapter: 5, index: 8, title: "迂回試験", summary: "障害物と開門を使い、表示中の目的地の流れを最後までつなげます。", goalCount: 13, deckPreset: .standardWithAllChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMostAndWithinMoves(maxFocusCount: 3, maxMoves: 30), scoreTarget: 420, unlockRequirement: .stageClear(stage57.id), impassableTilePoints: [GridPoint(x: 1, y: 1), GridPoint(x: 2, y: 3), GridPoint(x: 3, y: 1)], tileEffectOverrides: [GridPoint(x: 4, y: 3): .openGate(target: GridPoint(x: 2, y: 3))])

        return CampaignChapter(id: 5, title: "障害物と開門", summary: "障害物を避け、必要な道を開いて目的地へ向かう章。", stages: [stage51, stage52, stage53, stage54, stage55, stage56, stage57, stage58])
    }
}
