import Foundation

extension CampaignLibrary {
    static func buildChapter4() -> CampaignChapter {
        let stage41 = targetStage(chapter: 4, index: 1, title: "手札更新", summary: "NEXT更新マスを踏み、表示目的地の組み合わせを見直します。", goalCount: 8, deckPreset: .standard, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 290, unlockRequirement: .stageClear(CampaignStageID(chapter: 3, index: 8)), tileEffectOverrides: [GridPoint(x: 1, y: 3): .nextRefresh])
        let stage42 = targetStage(chapter: 4, index: 2, title: "無料フォーカス", summary: "無料フォーカスマスで、フォーカス回数を増やさず手札を整えます。", goalCount: 9, deckPreset: .standard, secondaryObjective: .finishWithinMoves(maxMoves: 21), scoreTarget: 315, unlockRequirement: .stageClear(stage41.id), tileEffectOverrides: [GridPoint(x: 3, y: 1): .freeFocus])
        let stage43 = targetStage(chapter: 4, index: 3, title: "カード温存", summary: "温存マスで使ったカードを残し、次の表示目的地にもつなげます。", goalCount: 9, deckPreset: .standardWithOrthogonalChoices, spawnRule: .fixed(GridPoint(x: 0, y: 0)), secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 315, unlockRequirement: .stageClear(stage42.id), tileEffectOverrides: [GridPoint(x: 2, y: 1): .preserveCard])
        let stage44 = targetStage(chapter: 4, index: 4, title: "ドラフト回復", summary: "ドラフトマスで手札を入れ替え、取りやすい目的地へ切り替えます。", goalCount: 10, deckPreset: .standardWithDiagonalChoices, spawnRule: .fixed(GridPoint(x: 4, y: 4)), secondaryObjective: .finishWithinMoves(maxMoves: 23), scoreTarget: 335, unlockRequirement: .stageClear(stage43.id), tileEffectOverrides: [GridPoint(x: 2, y: 3): .draft])
        let stage45 = targetStage(chapter: 4, index: 5, title: "シャッフル判断", summary: "シャッフルマスで手札が変わる前提で、踏むタイミングを選びます。", goalCount: 10, deckPreset: .standardWithAllChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 2), scoreTarget: 330, unlockRequirement: .stageClear(stage44.id), tileEffectOverrides: [GridPoint(x: 1, y: 1): .shuffleHand])
        let stage46 = targetStage(chapter: 4, index: 6, title: "補助カード入門", summary: "目的地補助カードで、表示中の目的地へ届く手を探します。", goalCount: 10, deckPreset: .targetLabAllIn, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), scoreTarget: 330, unlockRequirement: .stageClear(stage45.id), tileEffectOverrides: [GridPoint(x: 3, y: 3): .freeFocus])
        let stage47 = targetStage(chapter: 4, index: 7, title: "特殊マス補助", summary: "特殊マス補助カードで、手札更新や温存を拾うルートを作ります。", goalCount: 11, deckPreset: .targetLabAllIn, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 25), scoreTarget: 355, unlockRequirement: .stageClear(stage46.id), tileEffectOverrides: [GridPoint(x: 1, y: 3): .nextRefresh, GridPoint(x: 3, y: 1): .preserveCard])
        let stage48 = targetStage(chapter: 4, index: 8, title: "手札管理試験", summary: "更新、温存、ドラフトを使い、表示中の目的地を途切れず集めます。", goalCount: 11, deckPreset: .targetLabAllIn, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMostAndWithinMoves(maxFocusCount: 3, maxMoves: 25), scoreTarget: 350, unlockRequirement: .stageClear(stage47.id), tileEffectOverrides: [GridPoint(x: 0, y: 2): .nextRefresh, GridPoint(x: 2, y: 0): .preserveCard, GridPoint(x: 4, y: 2): .draft, GridPoint(x: 2, y: 4): .shuffleHand])

        return CampaignChapter(id: 4, title: "手札と補助効果", summary: "手札更新と補助カードで、目的地への流れを作り直す章。", stages: [stage41, stage42, stage43, stage44, stage45, stage46, stage47, stage48])
    }
}
