import Foundation

extension CampaignLibrary {
    static func buildChapter4() -> CampaignChapter {
        let stage41 = targetStage(chapter: 4, index: 1, title: "手札更新", summary: "NEXT更新マスを踏み、表示目的地の組み合わせを見直します。", goalCount: 8, deckPreset: .standard, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), twoStarScoreTarget: 365, scoreTarget: 290, unlockRequirement: .stageClear(CampaignStageID(chapter: 3, index: 8)), tileEffectOverrides: [GridPoint(x: 2, y: 5): .nextRefresh])
        let stage42 = targetStage(chapter: 4, index: 2, title: "無料フォーカス", summary: "無料フォーカスマスで、フォーカス回数を増やさず手札を整えます。", goalCount: 9, deckPreset: .standard, secondaryObjective: .finishWithinMoves(maxMoves: 23), twoStarScoreTarget: 420, scoreTarget: 335, unlockRequirement: .stageClear(stage41.id), tileEffectOverrides: [GridPoint(x: 5, y: 2): .freeFocus])
        let stage43 = targetStage(chapter: 4, index: 3, title: "カード温存", summary: "温存マスで使ったカードを残し、次の表示目的地にもつなげます。", goalCount: 9, deckPreset: .standardWithOrthogonalChoices, spawnRule: .fixed(GridPoint(x: 1, y: 1)), secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), twoStarScoreTarget: 420, scoreTarget: 335, unlockRequirement: .stageClear(stage42.id), tileEffectOverrides: [GridPoint(x: 4, y: 2): .preserveCard])
        let stage44 = targetStage(chapter: 4, index: 4, title: "ドラフト回復", summary: "ドラフトマスで手札を入れ替え、取りやすい目的地へ切り替えます。", goalCount: 10, deckPreset: .standardWithDiagonalChoices, spawnRule: .fixed(GridPoint(x: 6, y: 6)), secondaryObjective: .finishWithinMoves(maxMoves: 25), twoStarScoreTarget: 445, scoreTarget: 355, unlockRequirement: .stageClear(stage43.id), tileEffectOverrides: [GridPoint(x: 3, y: 5): .draft])
        let stage45 = targetStage(chapter: 4, index: 5, title: "シャッフル判断", summary: "シャッフルマスで手札が変わる前提で、踏むタイミングを選びます。", goalCount: 10, deckPreset: .standardWithAllChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 2), twoStarScoreTarget: 440, scoreTarget: 350, unlockRequirement: .stageClear(stage44.id), tileEffectOverrides: [GridPoint(x: 2, y: 2): .shuffleHand])
        let stage46 = targetStage(chapter: 4, index: 6, title: "再配布判断", summary: "無料フォーカスマスを踏むタイミングを選び、表示目的地へ手札を整えます。", goalCount: 10, deckPreset: .targetLabAllIn, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), twoStarScoreTarget: 440, scoreTarget: 350, unlockRequirement: .stageClear(stage45.id), tileEffectOverrides: [GridPoint(x: 5, y: 5): .freeFocus])
        let stage47 = targetStage(chapter: 4, index: 7, title: "更新と温存", summary: "NEXT更新と温存を使い分け、次の目的地へつながる手札を残します。", goalCount: 11, deckPreset: .targetLabAllIn, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 28), twoStarScoreTarget: 485, scoreTarget: 385, unlockRequirement: .stageClear(stage46.id), tileEffectOverrides: [GridPoint(x: 2, y: 6): .nextRefresh, GridPoint(x: 5, y: 2): .preserveCard])
        let stage48 = targetStage(chapter: 4, index: 8, title: "手札管理試験", summary: "更新、温存、ドラフトを使い、表示中の目的地を途切れず集めます。", goalCount: 11, deckPreset: .targetLabAllIn, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMostAndWithinMoves(maxFocusCount: 3, maxMoves: 28), twoStarScoreTarget: 475, scoreTarget: 380, unlockRequirement: .stageClear(stage47.id), tileEffectOverrides: [GridPoint(x: 1, y: 4): .nextRefresh, GridPoint(x: 4, y: 1): .preserveCard, GridPoint(x: 6, y: 4): .draft, GridPoint(x: 3, y: 6): .shuffleHand])

        return CampaignChapter(id: 4, title: "手札と補助効果", summary: "手札更新と特殊マスで、目的地への流れを作り直す章。", stages: [stage41, stage42, stage43, stage44, stage45, stage46, stage47, stage48])
    }
}
