import Foundation

extension CampaignLibrary {
    static func buildChapter6() -> CampaignChapter {
        let stage61 = targetStage(chapter: 6, index: 1, title: "レイの直線", summary: "連続移動カードで、遠い表示目的地へ一気に近づきます。", goalCount: 10, deckPreset: .directionalRayFocus, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), twoStarScoreTarget: 470, scoreTarget: 375, unlockRequirement: .stageClear(CampaignStageID(chapter: 5, index: 8)))
        let stage62 = targetStage(chapter: 6, index: 2, title: "加速制御", summary: "加速マスで一歩伸びる位置を読み、目的地への到達を早めます。", goalCount: 11, deckPreset: .directionalRayFocus, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 31), twoStarScoreTarget: 525, scoreTarget: 420, unlockRequirement: .stageClear(stage61.id), tileEffectOverrides: [GridPoint(x: 3, y: 2): .boost, GridPoint(x: 4, y: 5): .boost])
        let stage63 = targetStage(chapter: 6, index: 3, title: "減速で止まる", summary: "減速マスを使い、レイ型カードの行きすぎを止めます。", goalCount: 11, deckPreset: .directionalRayFocus, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), twoStarScoreTarget: 520, scoreTarget: 415, unlockRequirement: .stageClear(stage62.id), tileEffectOverrides: [GridPoint(x: 2, y: 4): .slow, GridPoint(x: 5, y: 3): .slow])
        let stage64 = targetStage(chapter: 6, index: 4, title: "加速と減速", summary: "伸ばすマスと止めるマスを見比べ、目的地へ必要な距離を作ります。", goalCount: 12, deckPreset: .directionalRayFocus, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 33), twoStarScoreTarget: 560, scoreTarget: 445, unlockRequirement: .stageClear(stage63.id), tileEffectOverrides: [GridPoint(x: 3, y: 2): .boost, GridPoint(x: 4, y: 5): .slow])
        let stage65 = targetStage(chapter: 6, index: 5, title: "過負荷の準備", summary: "過負荷マスで次のカードを温存し、連続回収の準備をします。", goalCount: 12, deckPreset: .standardWithAllChoices, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 3), twoStarScoreTarget: 550, scoreTarget: 440, unlockRequirement: .stageClear(stage64.id), tileEffectOverrides: [GridPoint(x: 4, y: 4): .overload])
        let stage66 = targetStage(chapter: 6, index: 6, title: "障害物レイ", summary: "障害物とレイ型カードを読み、通れる直線を選びます。", goalCount: 13, deckPreset: .directionalRayFocus, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithinMoves(maxMoves: 35), twoStarScoreTarget: 585, scoreTarget: 465, unlockRequirement: .stageClear(stage65.id), impassableTilePoints: [GridPoint(x: 2, y: 5), GridPoint(x: 5, y: 2)], tileEffectOverrides: [GridPoint(x: 3, y: 2): .boost, GridPoint(x: 4, y: 5): .slow])
        let stage67 = targetStage(chapter: 6, index: 7, title: "長距離総合", summary: "加速、減速、過負荷を読み、必要な時だけ大きく動きます。", goalCount: 13, deckPreset: .targetLabAllIn, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMost(maxFocusCount: 2), twoStarScoreTarget: 575, scoreTarget: 460, unlockRequirement: .stageClear(stage66.id), impassableTilePoints: [GridPoint(x: 1, y: 3), GridPoint(x: 6, y: 4)], tileEffectOverrides: [GridPoint(x: 2, y: 5): .boost, GridPoint(x: 5, y: 2): .slow, GridPoint(x: 4, y: 4): .overload])
        let stage68 = targetStage(chapter: 6, index: 8, title: "長距離制御試験", summary: "レイ型カードと特殊マスを使い、表示中の目的地を安定して集めます。", goalCount: 14, deckPreset: .directionalRayFocus, spawnRule: .chooseAnyAfterPreview, secondaryObjective: .finishWithFocusAtMostAndWithinMoves(maxFocusCount: 3, maxMoves: 37), twoStarScoreTarget: 615, scoreTarget: 490, unlockRequirement: .stageClear(stage67.id), impassableTilePoints: [GridPoint(x: 2, y: 2), GridPoint(x: 2, y: 5), GridPoint(x: 5, y: 2), GridPoint(x: 5, y: 5)], tileEffectOverrides: [GridPoint(x: 3, y: 2): .boost, GridPoint(x: 4, y: 5): .slow, GridPoint(x: 4, y: 4): .overload])

        return CampaignChapter(id: 6, title: "長距離制御", summary: "レイ型カードと加速・減速・過負荷で距離を調整する章。", stages: [stage61, stage62, stage63, stage64, stage65, stage66, stage67, stage68])
    }
}
